leftnav:
- identifier: 795744ed-9539-e398-5468-e753a4ef7bf7
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: aef94c59-0999-fcc7-e928-7698d1095913
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 55cb7652-fbc3-9016-7fdc-836f460b1f21
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: d27e7d98-c8e1-3902-924f-d953886f365a
  name: Assignments
  url: /pages/assignments
  weight: 40
- identifier: a71475eb-b75e-1fd6-628f-04266230cae1
  name: Study Materials
  url: /pages/study-materials
  weight: 50
